version: '3.5'
services:
    input:
        build:
            dockerfile: input/Dockerfile
            context: .
        ports:
            - 3033:3030
        restart: "unless-stopped"
        volumes:
            - ./data:/staging
            - mmm-simple:/fuseki-base/databases
        restart: unless-stopped
    crm:
        build:
            dockerfile: crm/Dockerfile
            context: .
        ports:
            - 3034:3030
        restart: "unless-stopped"
        depends_on:
          - input
        volumes:
            - mmm-crm:/fuseki-base/databases
        restart: unless-stopped
volumes:
    mmm-crm:
    mmm-simple:
