version: '3.5'
services:
    input-sdbm:
        build:
            context: .
            dockerfile: input/Dockerfile
        ports:
            - 3051:3030
        restart: "unless-stopped"
        volumes:
            - ./data/sdbm:/staging
            - mmm-sdbm:/fuseki-base/databases
        restart: unless-stopped
    input-bibale:
        build:
            context: .
            dockerfile: input/Dockerfile
        ports:
            - 3052:3030
        restart: "unless-stopped"
        volumes:
            - ./data/bibale:/staging
            - mmm-bibale:/fuseki-base/databases
        restart: unless-stopped
    input-bodley:
        build:
            context: .
            dockerfile: input/Dockerfile
        ports:
            - 3053:3030
        restart: "unless-stopped"
        volumes:
            - ./data/bodley:/staging
            - mmm-bodley:/fuseki-base/databases
        restart: unless-stopped
    transform:
        build:
            context: ./transform
        depends_on:
            - input-sdbm
            - input-bibale
            - input-bodley
        environment:
            - GEONAMES_KEY
            - GEONAMES_KEY2
            - GEONAMES_KEY3
            - GEONAMES_KEY4
            - GEONAMES_KEY5
            - GEONAMES_KEY6
        volumes:
            - ./output:/output
            - ./data/additional:/data
    crm:
        build:
            context: .
            dockerfile: crm/Dockerfile
        ports:
            - 3050:3030
        restart: "unless-stopped"
        volumes:
            - mmm-crm:/fuseki-base/databases
            - ./output:/output
        restart: unless-stopped

volumes:
    mmm-crm:
    mmm-sdbm:
    mmm-bibale:
    mmm-bodley:
