version: '3.5'
services:
    input-sdbm:
        build:
            dockerfile: input/Dockerfile
            context: .
        ports:
            - 3051:3030
        restart: "unless-stopped"
        volumes:
            - ./data/sdbm:/staging
            - mmm-sdbm:/fuseki-base/databases
        restart: unless-stopped
    input-bibale:
        build:
            dockerfile: input/Dockerfile
            context: .
        ports:
            - 3052:3030
        restart: "unless-stopped"
        volumes:
            - ./data/bibale:/staging
            - mmm-bibale:/fuseki-base/databases
        restart: unless-stopped
    input-bodley:
        build:
            dockerfile: input/Dockerfile
            context: .
        ports:
            - 3053:3030
        restart: "unless-stopped"
        volumes:
            - ./data/bodley:/staging
            - mmm-bodley:/fuseki-base/databases
        restart: unless-stopped
    crm:
        build:
            dockerfile: crm/Dockerfile
            context: .
        environment:
            - GEONAMES_KEY
            - GEONAMES_KEY2
            - GEONAMES_KEY3
            - GEONAMES_KEY4
            - GEONAMES_KEY5
            - GEONAMES_KEY6
        ports:
            - 3050:3030
        restart: "unless-stopped"
        depends_on:
          - input-sdbm
          - input-bibale
          - input-bodley
        volumes:
            - mmm-crm:/fuseki-base/databases
        restart: unless-stopped
volumes:
    mmm-crm:
    mmm-sdbm:
    mmm-bibale:
    mmm-bodley:
