version: '3.5'
services:
    input:
        build:
            dockerfile: Dockerfile.input
            context: .
        ports:
            - 3033:3030
    conversion:
        build:
            dockerfile: Dockerfile.conversion
            context: .
        ports:
            - 3034:3030
        depends_on:
          - "input"
